---
- name: generate /etc/sensu/conf.d/client.json
  template:
    src=sensu.client.json.j2
    dest=/etc/sensu/conf.d/client.json
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0640
    backup=yes
  notify: restart sensu client

- name: copy all the checks files
  copy:
    src=plugins/
    dest=/etc/sensu/plugins/
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0750
  notify:
    - restart sensu client

- name: install rubygems and dependencies (debian and ubuntu)
  apt: name={{ item }} state=present
  when: sensu_client_install_rubygems and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
    - ruby1.9.1-dev
    - ruby1.9.1

- name: install rubygems and dependencies (rhel)
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - ruby-devel
    - rubygems
  when: sensu_client_install_rubygems and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: install community plugins
  gem: name=sensu-plugin state=present
  when: sensu_client_install_community_plugins

- name: enable sensu-client to survive reboot
  service: name=sensu-client enabled=yes state=started
